### PR TITLE
kirby 3 rewrite

### PR DESCRIPTION
**Pull request by bnomei**
but still has open issue with global config file

Signed-off-by: Bruno Meilick <b@bnomei.com>

### CODE REVIEW

**Comment by bnomei** [comment]
should be commited to `kirby-3` branch but does not exist yet.

**Comment by jenstornell** [comment]
Thanks for your work on this. I already made the conversion before here: https://gist.github.com/jenstornell/abbe61ee793f0a8e58c325ea34c3d705 but because of the config option bug I did not release it.

I will compare mine to yours and see where your make more sense and somehow include it. I'll mention you in the readme file as thanks! =)

I'm on vacation and not sure when I have time for this. Maybe in 1-2 weeks.

**Comment by bnomei** [comment]
sure. enjoy your vacation.

**Comment by jenstornell** [comment]
I updated my plugin now to https://github.com/jenstornell/kirby-robots-writer/tree/kirby-3. No Composer support yet. I need to learn it myself before I add it.

Anyway, it's a start.

**Comment by bnomei** [comment]
about composer and plugins... right now its a bit awkward.
https://github.com/k-next/kirby/issues/762

**Pull request merged**
